### ISSUE TITLE
POINTPROP values in json output

### ISSUE THREAD

**Issue by wutobias** [aoterodelaroza/critic2#35]
Hi,

I'm interested in using critic2 on a larger set of molecules, so the ability to write information about critical points (with the `CPREPORT` option) to a json file and make it machine-readable is really awesome. However, I ran into a technical issue of which I hope to find some help. When running the following critic2 commands:

```
molecule pyridine.fchk
load pyridine.fchk
POINTPROP gtf
auto
CPREPORT pyridine.json
```

the gtf values are properly displayed on stdout however in the json file they are zero everywhere (same goes for other functions specified through `POINTPROP`):

```
      "pointprops": [{
        "id": 1,
        "name": "gtf",
        "expression": "gtf(1)",
        "value": 0.00000000000000E+00
      }],
```

Is there something missing in my input file or is this potentially a bug?

Regards,
Tobias

[pyridine.fchk.zip](https://github.com/aoterodelaroza/critic2/files/5467745/pyridine.fchk.zip)

**Comment by aoterodelaroza** [comment]
It's a bug, sorry. I just fixed it. Can you please pull and try again?

**Comment by wutobias** [comment]
Hi,

thanks for looking into this. Unfortunately it did not fix the issue. I still get zeros in the json file.

Regards,
Tobias

**Comment by aoterodelaroza** [comment]
Ooops, I should have used the example you provided instead of my own. Let me take a look at it again.

**Comment by aoterodelaroza** [comment]
Sone, sorry about that. Please, pull and try again.

**Comment by wutobias** [comment]
Excellent, now it works! I'm seeing the same values in stdout and json file. Thanks for the quick fix! :-) 

Regards,
Tobias
